print('Welcome back bro! lets quickly exchange those currencies you have left to INR')
pesos = int(input("Colombian Pesos left : "))
soles = int(input("Peruvian soles left : "))
reais = int(input("Brazilian reais left : "))
print('Great! now lets calculate and convert them .......')
peso_inr = (pesos * 0.026)
sole_inr = (soles * 27.15)
reai_inr = (reais * 19.09)
inr = (peso_inr + sole_inr + reai_inr)
print("You have saved", inr, "Rupees from the trip budget")